modLoader="javafml"
loaderVersion="[32,)"
license="MIT"
issueTrackerURL="https://github.com/Draylar/inmis/issues"

[[mods]]
modId="inmis"
version="1.0.0"
displayName="Inmis"
displayURL="https://github.com/Draylar/inmis"
logoFile="icon.png"
authors="Draylar"
contributors="shedaniel"
description='''
I need more inventory space!
'''